### 模型配置
model_name_or_path: /home/liwt/IVCP/LlamaFactory/outputs/qwen2_5_vl_sft_stage3_merged
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### 训练方法
stage: action_cls
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: all
lora_dropout: 0.05
use_dora: true

### 动作分类参数
num_action_classes: 174  # Something-Something V2 有 174 个类别
action_decoder_type: transformer  # 类别较多，使用 MLP 可能效果更好
action_decoder_hidden_size: 768  # MLP 中间层维度
action_decoder_num_transformer_layers: 2  # Transformer 层数
action_decoder_num_heads: 8 # Transformer 注意力头数
action_decoder_dropout: 0.1 # Dropout 比率
action_decoder_path: null
action_token_lr_scale: 0.1

### 数据集配置
dataset: sthsthv2_train
template: qwen2_vl
cutoff_len: 2048
max_samples: null
preprocessing_num_workers: 1
dataloader_num_workers: 4

### 输出配置
output_dir: outputs/qwen2_5vl_action_cls_sthsthv2_tr
logging_steps: 10
save_steps: 500
save_total_limit: 3
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: wandb

### 训练超参数
per_device_train_batch_size: 2  # Something-Something 数据集较大，可能需要减小 batch size
gradient_accumulation_steps: 8  # 有效 batch size = 2 * 8 = 16
learning_rate: 5.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.1
weight_decay: 0.01
bf16: true
ddp_timeout: 180000000

### 优化器配置
flash_attn: fa2
enable_liger_kernel: true

### 评估配置
# 使用独立的验证集
eval_dataset: sthsthv2_val
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
load_best_model_at_end: true
metric_for_best_model: eval_loss