### model
# model_name_or_path: /home/liwt/IVCP/model/Qwen/Qwen2.5-VL-3B-Instruct
model_name_or_path: /home/liwt/IVCP/LlamaFactory/outputs/qwen2_5_vl_sft_stage2_merged
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
use_dora: true

### dataset
# dataset: VideoEspresso_stage2  # video: mllm_video_demo
dataset: VideoEspresso_stage3  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 2048
# max_samples: 1000
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: outputs/qwen2_5vl_sft_stage3/lora/sft
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

flash_attn: fa2
enable_liger_kernel: true

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
